// renderer/components/ui/Instance.tsx
import { HiPlay, HiPencil, HiCog6Tooth } from "react-icons/hi2";

interface InstanceProps {
  name?: string;
  imageUrl?: string;
  id?: any;
}

export default function Instance({ id, imageUrl, name }: InstanceProps) {
  const checkImageUrl = () =>
    imageUrl ? `url(${imageUrl})` : "url(/theme/5.png)";

  return (
    <div
      className="bg-cover bg-no-repeat bg-clip-content
            border border-stroke-1 group rounded-in w-full aspect-video h-auto flex flex-col place-content-between"
      style={{
        backgroundImage: `linear-gradient(to bottom,rgba(0,0,0,0.2),rgba(0,0,0,0.8)), ${checkImageUrl()}`,
      }}
    >
      <div className="fg-3 backdrop-blur-main h-fit w-full rounded-t-[7.55px] flex gap-48 px-32 py-16 opacity-0 group-hover:opacity-100 duration-150">
        <button>
          <HiPlay className="w-[25px] h-[25px] hover-active-effect" />
        </button>
        <button>
          <HiPencil className="w-[25px] h-[25px] hover-active-effect" />
        </button>
        <button>
          <HiCog6Tooth className="w-[25px] h-[25px] hover-active-effect" />
        </button>
      </div>
      <h3 className="text-3 font-medium m-32">{name}</h3>
    </div>
  );
}

// components/Instance.vue
<template>
    <div
        :class="[
            {
                'instance-card-base w-[229px] h-[275px] group': small
            },
            {
                'instance-card-base w-[350px] h-[275px] group': medium
            },
            {
                'instance-card-base w-[420px] h-[275px] group': large
            },
            {
                'instance-card-base w-[525px] h-[275px] group': xl
            }
        ]"
    >
        <div class="opacity-0 flex group-hover:opacity-100 duration-200 transition-all bg-[#0f0f0f]/60 backdrop-blur-lg w-full h-fit p-[16px] rounded-[8px] gap-[32px]">
            <button v-tooltip="'Play'" class="hover:scale-105 hover:text-brand-blue-1 active:scale-90 duration-200 w-fit h-fit">
                <nuxt-icon name="play" />
            </button>
            <button v-tooltip="'Instance Settings'" class="hover:scale-105 hover:text-brand-blue-1 active:scale-90 duration-200 w-fit h-fit">
                <nuxt-icon name="settings" />
            </button>
            <button v-tooltip="'Edit Card'" class="hover:scale-105 hover:text-brand-blue-1 active:scale-90 duration-200 w-fit h-fit">
                <nuxt-icon name="edit" />
            </button>
        </div>
        <h2
            :class="[
                {
                    'text-[32px] font-medium leading-10 px-[16px] pb-[16px] cursor-default': small
                },
                {
                    'text-[32px] font-medium leading-10 px-[16px] pb-[16px] cursor-default': medium
                },
                {
                    'text-[32px] font-medium leading-10 px-[16px] pb-[16px] cursor-default': large
                },
                {
                    'text-[32px] font-medium leading-10 px-[16px] pb-[16px] cursor-default': xl
                }
            ]"
            >Instance</h2
        >
    </div>
</template>

<script>
export default {
    props: {
        size: {
            type: String,
            default: 'medium'
        }
    },

    computed: {
        small() {
            return this.size === 'small'
        },
        medium() {
            return this.size === 'medium'
        },
        large() {
            return this.size === 'large'
        },
        xl() {
            return this.size === 'xl'
        }
    }
}
</script>
