// components/ui/SideNav.tsx
"use client";

import Image from "next/image";
import Link from "next/link";
import {
    HiRectangleStack,
    HiMiniUserGroup,
    HiCog6Tooth,
    HiMiniNewspaper,
    HiMiniQuestionMarkCircle,
} from "react-icons/hi2";
import { usePathname } from "next/navigation";

export default function SideNav() {
    const isCurrentPage = (path: string) => usePathname() === path;
    return (
        <div className="w-fit flex flex-col place-content-between align-middle place-items-center">
            <Link href={"/"}>
                <Image
                    src={"/logo.png"}
                    alt="HQLauncher Logo"
                    width={50}
                    height={50}
                    className="hover-active-effect"
                />
            </Link>

            <div className="flex flex-col gap-32">
                <Link href={"/"}>
                    <HiRectangleStack
                        className={`w-[28px] h-[28px] hover-active-effect ${
                            isCurrentPage("/") ? "text-selected" : ""
                        }`}
                    />
                </Link>
                <Link href={"/accounts"}>
                    <HiMiniUserGroup
                        className={`w-[28px] h-[28px] hover-active-effect ${
                            isCurrentPage("/accounts") ? "text-selected" : ""
                        }`}
                    />
                </Link>
                <Link href={"/settings"}>
                    <HiCog6Tooth className={`w-[28px] h-[28px] hover-active-effect ${
                            isCurrentPage("/settings") ? "text-selected" : ""
                        }`} />
                </Link>
                <Link href={"/news"}>
                    <HiMiniNewspaper className={`w-[28px] h-[28px] hover-active-effect ${
                            isCurrentPage("/news") ? "text-selected" : ""
                        }`} />
                </Link>
                <Link href={"/"}>
                    <HiMiniQuestionMarkCircle className="w-[28px] h-[28px] hover-active-effect" />
                </Link>
            </div>
        </div>
    );
}

// components/SideNav.vue
<template>
	<div class="flex flex-col place-content-between w-full h-full">
		<nuxt-link href="/">
			<nuxt-img
				src="/logo.png"
				class="w-[50px] h-[50px]"
				alt="HQLauncher Logo"
			/>
		</nuxt-link>
		<div class="flex flex-col gap-[32px] align-middle place-items-center">
			<NuxtLink
				to="/"
				class="hover:scale-95 transition-all duration-200 active:scale-90"
			>
				<nuxt-icon
					name="instances-list"
					:class="[
						{
							'text-[25px] selected': instances,
						},
						{
							'text-[25px]': settings,
						},
						{
							'text-[25px]': accounts,
						},
						{
							'text-[25px]': news,
						},
					]"
				/>
			</NuxtLink>
			<NuxtLink
				to="/accounts"
				class="hover:scale-95 transition-all duration-200 active:scale-90"
			>
				<nuxt-icon
					name="accounts"
					:class="[
						{
							'text-[25px]': instances,
						},
						{
							'text-[25px]': settings,
						},
						{
							'text-[25px] selected': accounts,
						},
						{
							'text-[25px]': news,
						},
					]"
				/>
			</NuxtLink>
			<NuxtLink
				to="/settings"
				class="hover:scale-95 transition-all duration-200 active:scale-90"
			>
				<nuxt-icon
					name="settings"
					:class="[
						{
							'text-[25px]': instances,
						},
						{
							'text-[25px] selected': settings,
						},
						{
							'text-[25px]': accounts,
						},
						{
							'text-[25px]': news,
						},
					]"
				/>
			</NuxtLink>
			<NuxtLink
				to="/news"
				class="hover:scale-95 transition-all duration-200 active:scale-90"
			>
				<nuxt-icon
					name="news"
					:class="[
						{
							'text-[25px]': instances,
						},
						{
							'text-[25px]': settings,
						},
						{
							'text-[25px]': accounts,
						},
						{
							'text-[25px] selected': news,
						},
					]"
				/>
			</NuxtLink>
			<NuxtLink
				to="/"
				class="hover:scale-95 transition-all duration-200 active:scale-90"
			>
				<nuxt-icon name="help" class="text-[25px]" />
			</NuxtLink>
		</div>
	</div>
</template>

<script>
export default {
	props: {
		selected: {
			type: String,
			default: "instances",
		},
	},

	computed: {
		instances() {
			return this.selected === "instances";
		},
		settings() {
			return this.selected === "settings";
		},
		accounts() {
			return this.selected === "accounts";
		},
		news() {
			return this.selected === "news";
		},
	},
};
</script>
